// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EEFWebAppi1w3.Data.Models;

public partial class Libro
{
    public int IdLibro { get; set; }

    public string Isbn { get; set; }

    public string Nombre { get; set; }

    public string FechaPublicacion { get; set; }

    public string Genero { get; set; }

    public int Autor { get; set; }

    public virtual Autor AutorNavigation { get; set; }
}